[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "hapiserver_demo"
version = "0.0.1"
requires-python = ">=3.8"
dependencies = [
  "urllib3",
  "hapiserver @ git+https://github.com/rweigel/server-python.git@main"
]

[project.optional-dependencies]
test = [
  "a2wsgi",
  "flask",
  "httpx2",
  "pytest"
]

[tool.setuptools]
packages = ["hapiserver_demo"]

[tool.setuptools.package-dir]
hapiserver_demo = "src"

[tool.setuptools.package-data]
hapiserver_demo = ["*.json"]
